services:
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: dev_wiremock
    ports:
     - "8082:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]